spring:
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: 'true'
        id:
          new_generator_mapping: 'false'
  profiles:
    active: '@activatedProperties@'
info:
  application:
    version: '@project.version@'