# Configuracion general
info:
  application:
    name: '@name@'
    description: '@description@'
    version: '@version@'
server:
  port: 8080
  error:
    include-message: always
springdoc:
  swagger-ui:
    path: /manager/index.html
  api-docs:
    path: /v3/api

# Seguridad
spring:
  application:
    name: '@name@'

# Datasources
  datasource:
    url: jdbc:mariadb://localhost:3306/manager?autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    databasePlatform: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDB103Dialect